### ISSUE TITLE
tolerance and clicks on the screw

### ISSUE THREAD

**Issue by dasb00ter** [GatoMiopia/Klipper_Z_Tramming#2]
Im using sv06 plus latest Klipper and Mainsail. At first it seemed the dialogue popup wasn't working but I changed the tolerance to .02 and the dialogue popped up but the suggested rotation is 0.0 minutes is that b/c .05 is one click on the motors? 

```
Set tolerance is 0.02 mm

Right is 0.04 mm higher

Turn the right lead screw 0:0 CCW

01:20 means 1 full turn and 20 minutes, CW=clockwise, CCW=counter-clockwise
```

I guess also asking why you choose to measure at the front of the bed and screw locations?

**Comment by GatoMiopia** [comment]
The popup will only show up if your tramming needs adjusting. After adjusting, another popup should show up telling you to restart your print. If everything is all right, nothing should show up.

I had it popup every time before, but found that to be very annoying at times.

About the tolerance and screw rotations, the reason I've let the default tolerance to .05 is because that's really enough. I've tested .02 for quite some time and found that it would stop the print for simple probe tolerances. If it errors and you simply run it again it would work as if nothing happened.
For that reason I recommend sticking to the .05, you'll have less headache.

The problem with the adjustment is the same, 0.01x is to small to calculate in minutes, it would have to say seconds and at that point there is to point to it.

Lastly, about the measuring points. At the beginning I measured it at the maximum X in the middle of the bed, but noticed that warping played a big role the measurements. Using the screws was the best way I found to keep it as consistent as possible.

**Comment by dasb00ter** [comment]
May I ask as an aside and as fellow sv06 + owner who is a novice what does your print routine consist of? Do you heat hot end and build plate then tram then print. I've only just run your macro as a standalone. It takes me awhile to actually get a print started.

**Comment by GatoMiopia** [comment]
You can absolutely use my macro just as a calibration step, that was one of my goals with it, as well as being possible to automate it.

My print routine was quite long as well to keep it consistent, that's why I automated it as much as possible. 

Today, it is as following:
(I'll put bigger notes referenced at the end)
- Slice file and send it to klipper
- Turn printer on
- Home it
- Z offset (usually just on the first print of the day)
- Put fillament in it (*1)
- Move bed forward to clean it with isopropyl alcohol and a paper towel
- Click print

Here we enter into my print start macro, and it goes as follows:

- Homes the printer
- Z Tramming (Here I wait to see if it'll need manual input)
- Heats up only the bed (*2)
- Set the Hotend to 150C (that's below oozing temp on ABS)
- Bed Mesh with KAMP
- Set Hotend to printing temp (250C) and wait
- Print Purge Line (with KAMP)
- Print

*1 - I don't purge it because I usually just use one fillament, so I've calibrated my purge line to account for it. If you use multiple fillaments or fillament types I'd recommend doing at least a purge.

*2 - I heat up the bed alone because I print exclusively ABS, and it can be quite slow to get to 100C. By heating up the bed only I can reduce oozing and power consumption from keeping the nozzle at temp.

I have also automated a coldpull in my Print End macro. It took me quite some time to tune it, but it was very useful to remove fillament after printing.

If you print PLA, I don't think you'd need that, but as I almost exclusively print ABS which is more hydroscopic and live in a very humid place I started to store my fillament in vacuum bags over night. This keeps the fillament dry for longer, but I also have a macro for drying fillament that I use from time to time.

Hope it helps more than confuses, as I know my process can be very overwhelming to other people.

I am also a programmer and quite like to tinker with the printer as shown in this giant response, most of it is not needed, but can be quite helpful and I had fun automating it hahaha.
